//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnionDeTablas.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles_usuarios
    {
        public int Id_RolUsuario { get; set; }
        public int IdUsuario { get; set; }
        public string TipoDeRol { get; set; }
    
        public virtual tb_usuarios tb_usuarios { get; set; }
    }
}
